Fix: send outcome functions when no handler is set -> pass empty function
OneSignal/react-native-onesignal pull request #1356
Opened 2022-01-30 22:37 UTC by nan-li

## One Line Description
Pass empty function handler over the bridge for send outcome functions if user doesn't set handlers.

## Details
Fixes https://github.com/OneSignal/react-native-onesignal/issues/1348. The 3 functions related to sending outcomes used to have a default `handler=function(){}` in the function definition if a user does not pass a handler in (`sendOutcome`, `sendUniqueOutcome`, `sendOutcomeWithValue`).

This was removed from the function definition when the SDK was converted to TypeScript in #1312, but the body of the function didn't check and set the handler to an empty function before passing it over the bridge, leading to crashes.

```
static sendOutcome(name, handler=function(){})

static sendOutcome(name: string, handler?: (event: OutcomeEvent) => void): void
```

Now, add a check for the `handler` and set to empty function if not provided.

2022-02-01 19:53 UTC, rgomezp requested changes
Looks good. Just one nit:

We've moved away from one-line conditionals with no brackets.

So make sure to wrap the line with brackets like so:

```js
if (!handler) {
   handler = function(){};
}
```

2022-02-01 21:11 UTC, nan-li commented
> We've moved away from one-line conditionals with no brackets.
> 
> So make sure to wrap the line with brackets like so:
> 
> ```js
> if (!handler) {
>    handler = function(){};
> }
> ```

Got it! Is this the case across all the SDKs (I see one-line conditionals without brackets in the Android SDK)?

2022-02-01 23:23 UTC, rgomezp commented
I'll defer to @jkasten2 on the Android SDK. But at least on all JS-based SDKs, yes let's try to avoid those going forward.

2022-02-01 23:24 UTC, rgomezp approved these changes
LGTM

2022-02-05 00:49 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/react-native-onesignal/1356#-:-Mv6LpBgDvfONv2TpGuS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nan-li)



<!-- Sent from Reviewable.io -->

2022-02-05 02:35 UTC, merged