[User Model] Run Prettier
OneSignal/react-native-onesignal pull request #1528
Opened 2023-06-20 18:21 UTC by jennantilla

# Description
## One Line Summary
Run Prettier on code files to address [Test] Linting build failure.

## Details

### Motivation
Fix [Test] Linting build failure with beta-2 naming updates.

## Manual testing
Ran project after running Prettier to ensure no additional failures.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-06-26 21:31 UTC, nan-li requested changes
Most of the lint changes LGTM except the migration guide since it is poor at linting tables.

I think we have to manually go through the migration guide, or exclude the migration guide from lint rules. Most of the changes look good and I agree with the spacing changes, etc, but it doesn't lint the tables well.

We can exclude the migration guide from linting but I do like some of the changes it made. So, I think we can accept most of the changes it made on non-table parts, and manually do the table changes ourselves to comply with the lint rules.

2023-06-26 21:31 UTC, nan-li commented on tsconfig.json
> +    "noUnusedLocals": true
I don't know why they removed the last comma here (which I think it should be there), but in other examples, added the last comma. Such as in "src/models/Subscription.ts" they added a comma after `Ephemeral` 🤷🏻‍♀️

2023-06-26 21:31 UTC, nan-li commented on MIGRATION_GUIDE.md
I think we have to manually go through the migration guide, or exclude the migration guide from lint rules. Most of the changes look good and I agree with the spacing changes, etc, but it doesn't lint the tables well.

2023-06-30 20:06 UTC, nan-li approved these changes

2023-07-10 17:21 UTC, jkasten2 approved these changes

2023-07-24 22:34 UTC, merged