Add public `getTags` method
OneSignal/react-native-onesignal pull request #1609
Opened 2023-12-04 22:59 UTC by jennantilla

# Description
## One Line Summary
Add public `OneSignal.User.getTags()` method to return local tags for the current user.

## Details
Add `getTags` public method that will return local tags for the current user on both Android and iOS.

### Motivation
We removed the `getTags` method in v5 of the SDKs to discourage use of OneSignal tags as a data store. We have heard feedback from app developers that they have a need for this method still, so we are adding back an implementation to return the local tags.

### Scope
Keep note it returns the local tags and not via a server fetch so any tags added mid-session through the REST API will not be reflected.

# Testing
## Unit testing
None

## Manual testing
Successfully call new method getTags on iPhone 15 emulator running iOS 17.0.1 and Pixel 7 running Android 14.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [x] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/react-native-onesignal/1609)

2023-12-05 00:44 UTC, nan-li approved these changes

2023-12-05 02:57 UTC, nan-li requested changes

2023-12-05 02:57 UTC, nan-li commented on android/src/main/java/com/onesignal/rnonesignalandroid/RNOneSignal.java
> +        }
Looking at this again, there is no need for the try-catch. We would need it if we are working with JSON and need to handle possible JSONExceptions, but we aren't doing so here. 
I did notice that we have a lot of redundant try-catches in this file that can potentially hide problems. May be worth cleaning up in a future refactor.

2023-12-05 17:41 UTC, nan-li approved these changes

2023-12-05 18:31 UTC, merged

2024-06-15 07:32 UTC, rgomezp commented
@emawby @nan-li @jennantilla why is getTags asynchronous here? This is not consistent with our other SDKs and with the description "returns local tags" https://documentation.onesignal.com/docs/mobile-sdk-reference#gettags

2024-06-16 16:39 UTC, nan-li commented
@rgomezp The call needs to go over the bridge to call the native function and receive the result. It's not consistent with the native SDKs since they don't need to do this.

2024-06-17 17:02 UTC, rgomezp commented
@nan-li I forgot about that limitation. Thanks!