AndroidX update
OneSignal/react-native-onesignal pull request #813
Opened 2019-07-23 19:46 UTC by amadeu01

To support RN 0.60.+ it must have AndroidX support.

2019-07-23 20:13 UTC, douglaskayama approved these changes

2019-07-24 22:14 UTC, jkasten2 requested changes
Thanks for the PR. However this would break compatibility with projects older than React Native 0.60.0. I'll follow up with more details in a comment.

2019-07-24 22:21 UTC, jkasten2 commented
We are planning our upgrade to AndroidX, however this needs to be done on our made OneSignal-Android-SDK which this includes first. Since Google made a breaking change for this migration they did create a tool called [Jetifier](https://developer.android.com/jetpack/androidx/migrate#migrate) that will migrate the imports, even for compiled .jar.

In the meantime there is an easier way to add Jetifier than following Google's guide above. You can add a npm package called [jetifier package](https://www.npmjs.com/package/jetifier), noted from 
[React Native 0.60.0 release notes](https://facebook.github.io/react-native/blog/2019/07/03/version-60#androidx-support).

2019-07-24 23:02 UTC, amadeu01 commented
@jkasten2 thanks for your reply. But, the js `jetifier`, couldn't handle well the projects after add the first lines of script to the `app/build.gradle` (the setup for Android), that is why I did this PR.

For projects that are older than RN 0.60, I would say to keep different branches to support legacy 
version.

2019-07-25 00:38 UTC, jkasten2 commented
@amadeu01 I tried creating a new react native project with `react-native init` and wasn't able to reproduce an issue. This created a React Native 0.60.4 project for me. I noticed too that the new React project actually already enabled Jetifier by default, as `gradle.properties` contained these lines when I checked.
```gradle

android.useAndroidX=true
android.enableJetifier=true
``` 

Are you upgrading from a pre-0.60 project?

Are you running into a specific error we can look into?

Can you share a project reproducing the issue?

2019-07-25 13:35 UTC, amadeu01 commented
hi @jkasten2 

> 1. Are you upgrading from a pre-0.60 project?

Yes, I am.

> 2. Are you running into a specific error we can look into?
> 3. Can you share a project reproducing the issue?

I'll try to reproduce the issue with some new project with `react-native init`

2019-07-29 19:43 UTC, jkasten2 commented
@amadeu01 We recently fixed a bug with the OneSignal-Gradle-Plugin that was conflicting with Jetifier. Let us know if this fixed the issue for you.
https://github.com/geektimecoil/react-native-onesignal/issues/800#issuecomment-516133396

2019-07-29 20:05 UTC, amadeu01 commented
@jkasten2 just checked your comment, I'm going to test and will let you know.

BTW, don't you think this line `implementation 'com.android.support:cardview-v7:27.1.1'` can be remove, one there is no metion to cardview in the Android project?

2019-07-29 20:40 UTC, amadeu01 commented
@jkasten2 I'm getting this `OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:28.0.0' -> 28 to prevent compile errors! Recommend updating your project's compileSdkVersion!`

2019-07-31 18:09 UTC, jkasten2 commented
@amadeu01 I haven't been able to reproduce that specific warning. I don't believe it will create any issues since it is the same version, just a different format.

However if you can provide details on reproducing the issue can you open a new ticket below with as much detail as possible?
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues

If you are still seeing any issues with setting up the OneSignal React Native SDK please open a issue here.

Thanks.

2019-07-31 18:09 UTC, closed without merging